apiVersion: apps/v1
kind: Deployment
metadata:
  name: part-1
  namespace: ${NAMESPACE}
  labels:
    app: part-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: part-1
  template:
    metadata:
      labels:
        app: part-1
    spec:
      containers:
        - name: part-1
          image: ghcr.io/username/nodejs-k8s-app:latest
          imagePullPolicy: Always
          env:
            - name: APP_NAME
              value: "my-configured-app"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: part-1
  namespace: ${NAMESPACE}
spec:
  selector:
    app: part-1
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
